if: tag IS blank

env:
  global:
    CONAN_PRINT_RUN_COMMANDS: 1
    CONAN_LOG_RUN_TO_OUTPUT: 1

    CONAN_REFERENCE: icu/64.2+2
    CONAN_USERNAME: odant
    CONAN_CHANNEL: testing
    CONAN_STABLE_CHANNEL: stable

    CONAN_UPLOAD: https://conan.kysa.me
    CONAN_LOGIN_USERNAME: travis
    CONAN_STABLE_BRANCH_PATTERN: release/*

linux: &linux_build
  os: linux
  dist: xenial
  sudo: false
  language: python
  python: 3.7
  services:
    - docker

matrix:
  include:
    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 6
       CONAN_DOCKER_IMAGE: conanio/gcc6
       CONAN_ARCHS: x86_64

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 6
       CONAN_DOCKER_IMAGE: conanio/gcc6
       CONAN_ARCHS: x86

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 7
       CONAN_DOCKER_IMAGE: conanio/gcc7
       CONAN_ARCHS: x86_64

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 7
       CONAN_DOCKER_IMAGE: conanio/gcc7
       CONAN_ARCHS: x86

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_ARCHS: x86_64

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_ARCHS: x86

install:
  - pip install conan
  - pip install conan_package_tools
  - conan user

script:
  - python build.py
