if: tag IS blank

env:
  global:
    CONAN_PRINT_RUN_COMMANDS: 1
    CONAN_LOG_RUN_TO_OUTPUT: 1

    CONAN_REFERENCE: icu/68.1+0
    CONAN_USERNAME: odant
    CONAN_CHANNEL: testing
    CONAN_STABLE_CHANNEL: stable

    CONAN_UPLOAD: https://conan.kysa.me
    CONAN_LOGIN_USERNAME: travis
    CONAN_STABLE_BRANCH_PATTERN: release/*

#    CONAN_OPTIONS:
    CONAN_SHARED_OPTION_NAME: False
    CONAN_PURE_C: False

    CONAN_USE_DOCKER: 1

linux: &linux_build
  os: linux
  dist: bionic
  language: python
  python: 3.8
  services:
    - docker

matrix:
  include:
    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 8
       CONAN_DOCKER_IMAGE: conanio/gcc8
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_GCC_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/gcc9
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86_64
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9-x86
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9-x86
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=True,icu:shared=True

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9-x86
       CONAN_BUILD_TYPES: Release
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

    - <<: *linux_build
      env:
       CONAN_CLANG_VERSIONS: 9
       CONAN_DOCKER_IMAGE: conanio/clang9-x86
       CONAN_BUILD_TYPES: Debug
       CONAN_ARCHS: x86
       CONAN_OPTIONS: icu:with_unit_tests=False,icu:shared=False

install:
  - pip install conan
  - pip install conan_package_tools
  - conan user

script:
  - python build.py

